permalink: /:year/:month/:day/:title.html
markdown: kramdown
#pygments: true
highlighter:  pygments
lsi:          false
excerpt_separator: "\n\n"

kramdown:
  input: GFM

# 作者信息
author: 
  name: 阿释密达沙加
  email: ashimidashajia@126.com
  link: http://ashimidashajia.github.io/
#  weibo: http://weibo.com/yansu0711
#  github: http://github.com/suyan

# 站点信息
highlighter: pygments
title: 沙罗双树园 
description: 一朝入此门，从此红尘了如空
url: http://ashimidashajia.github.io/
rss_url: /pages/atom.xml

# avatar头像及Favicon
avatar: http://7u2ho6.com1.z0.glb.clouddn.com/site-avatar.png
favicon: http://7u2ho6.com1.z0.glb.clouddn.com/site-favicon.ico

# google analytics 设置
ga:
  id: UA-54767140-1
  url: yansu.org

# disqus 设置
disqus:
  shortname: suyan-zh